/** @filedesc Fallback FEL built-in function catalog mirrored from the Rust runtime metadata. */
import type { FELBuiltinFunctionCatalogEntry } from './runtime.js';

// Keep this list in lockstep with crates/fel-core/src/extensions.rs.
export const FALLBACK_BUILTIN_FEL_FUNCTION_CATALOG: FELBuiltinFunctionCatalogEntry[] = [
    { name: 'sum', category: 'aggregate', signature: 'sum(array<number>) -> number', description: 'Returns the sum of numeric elements in an array.' },
    { name: 'count', category: 'aggregate', signature: 'count(array<any>) -> number', description: 'Counts non-null elements in an array.' },
    { name: 'avg', category: 'aggregate', signature: 'avg(array<number>) -> number', description: 'Returns the arithmetic mean of numeric array elements.' },
    { name: 'min', category: 'aggregate', signature: 'min(array<any>) -> any', description: 'Returns the smallest non-null element in an array.' },
    { name: 'max', category: 'aggregate', signature: 'max(array<any>) -> any', description: 'Returns the largest non-null element in an array.' },
    { name: 'countWhere', category: 'aggregate', signature: 'countWhere(array<any>, predicate) -> number', description: 'Counts elements whose predicate evaluates to true.' },
    { name: 'length', category: 'string', signature: 'length(string | array<any>) -> number', description: 'Returns the number of characters in a string or elements in an array.' },
    { name: 'contains', category: 'string', signature: 'contains(string, string) -> boolean', description: 'Returns true when the first string contains the second as a substring.' },
    { name: 'startsWith', category: 'string', signature: 'startsWith(string, string) -> boolean', description: 'Returns true when a string starts with the given prefix.' },
    { name: 'endsWith', category: 'string', signature: 'endsWith(string, string) -> boolean', description: 'Returns true when a string ends with the given suffix.' },
    { name: 'substring', category: 'string', signature: 'substring(string, number, number?) -> string', description: 'Extracts a substring using 1-based start and optional length.' },
    { name: 'replace', category: 'string', signature: 'replace(string, string, string) -> string', description: 'Replaces occurrences of a substring with a new value.' },
    { name: 'upper', category: 'string', signature: 'upper(string) -> string', description: 'Converts a string to uppercase.' },
    { name: 'lower', category: 'string', signature: 'lower(string) -> string', description: 'Converts a string to lowercase.' },
    { name: 'trim', category: 'string', signature: 'trim(string) -> string', description: 'Removes leading and trailing whitespace from a string.' },
    { name: 'matches', category: 'string', signature: 'matches(string, string) -> boolean', description: 'Returns true when a string matches a regular expression pattern.' },
    { name: 'format', category: 'string', signature: 'format(string, ...any) -> string', description: 'Interpolates indexed placeholders like {0} and sequential %s markers with argument values.' },
    { name: 'round', category: 'numeric', signature: 'round(number, number?) -> number', description: 'Rounds a number using banker’s rounding with optional precision.' },
    { name: 'floor', category: 'numeric', signature: 'floor(number) -> number', description: 'Rounds a number down to the nearest integer.' },
    { name: 'ceil', category: 'numeric', signature: 'ceil(number) -> number', description: 'Rounds a number up to the nearest integer.' },
    { name: 'abs', category: 'numeric', signature: 'abs(number) -> number', description: 'Returns the absolute value of a number.' },
    { name: 'power', category: 'numeric', signature: 'power(number, number) -> number', description: 'Raises a base to a numeric exponent.' },
    { name: 'today', category: 'date', signature: 'today() -> date', description: 'Returns the current local date from the runtime context.' },
    { name: 'now', category: 'date', signature: 'now() -> dateTime', description: 'Returns the current local datetime from the runtime context.' },
    { name: 'year', category: 'date', signature: 'year(date) -> number', description: 'Extracts the year component from a date.' },
    { name: 'month', category: 'date', signature: 'month(date) -> number', description: 'Extracts the month component from a date.' },
    { name: 'day', category: 'date', signature: 'day(date) -> number', description: 'Extracts the day component from a date.' },
    { name: 'hours', category: 'date', signature: 'hours(string) -> number', description: 'Extracts the hour component from a HH:MM:SS time string.' },
    { name: 'minutes', category: 'date', signature: 'minutes(string) -> number', description: 'Extracts the minute component from a HH:MM:SS time string.' },
    { name: 'seconds', category: 'date', signature: 'seconds(string) -> number', description: 'Extracts the second component from a HH:MM:SS time string.' },
    { name: 'time', category: 'date', signature: 'time(number, number, number) -> string', description: 'Builds a HH:MM:SS time string from numeric parts.' },
    { name: 'timeDiff', category: 'date', signature: 'timeDiff(laterTime, earlierTime) -> number', description: 'Returns the difference in seconds between laterTime and earlierTime.' },
    { name: 'dateDiff', category: 'date', signature: 'dateDiff(laterDate, earlierDate, unit) -> number', description: 'Returns the difference between laterDate and earlierDate in the requested unit.' },
    { name: 'dateAdd', category: 'date', signature: 'dateAdd(date, number, unit) -> date', description: 'Adds a number of days, months, or years to a date.' },
    { name: 'if', category: 'logical', signature: 'if(boolean, any, any) -> any', description: 'Returns the second argument when the condition is true, otherwise the third.' },
    { name: 'coalesce', category: 'logical', signature: 'coalesce(...any) -> any', description: 'Returns the first non-null argument.' },
    { name: 'empty', category: 'logical', signature: 'empty(any) -> boolean', description: 'Returns true for null, empty strings, and empty arrays.' },
    { name: 'present', category: 'logical', signature: 'present(any) -> boolean', description: 'Returns true when a value is not empty.' },
    { name: 'selected', category: 'logical', signature: 'selected(array<any>, any) -> boolean', description: 'Returns true when a choice value is present in a selected choices array.' },
    { name: 'isNumber', category: 'type', signature: 'isNumber(any) -> boolean', description: 'Returns true when a value is a number.' },
    { name: 'isString', category: 'type', signature: 'isString(any) -> boolean', description: 'Returns true when a value is a string.' },
    { name: 'isDate', category: 'type', signature: 'isDate(any) -> boolean', description: 'Returns true when a value is a date or datetime.' },
    { name: 'isNull', category: 'type', signature: 'isNull(any) -> boolean', description: 'Returns true when a value is null.' },
    { name: 'typeOf', category: 'type', signature: 'typeOf(any) -> string', description: 'Returns the FEL type name of a value.' },
    { name: 'number', category: 'cast', signature: 'number(any) -> number', description: 'Casts strings, booleans, and numbers to number values.' },
    { name: 'string', category: 'cast', signature: 'string(any) -> string', description: 'Casts a value to its string representation.' },
    { name: 'boolean', category: 'cast', signature: 'boolean(any) -> boolean', description: 'Casts a value to boolean using FEL conversion rules.' },
    { name: 'date', category: 'cast', signature: 'date(any) -> date', description: 'Parses an ISO date or datetime string into a FEL date value.' },
    { name: 'money', category: 'money', signature: 'money(number, string) -> money', description: 'Constructs a money value from an amount and currency code.' },
    { name: 'moneyAmount', category: 'money', signature: 'moneyAmount(money) -> number', description: 'Extracts the numeric amount from a money value.' },
    { name: 'moneyCurrency', category: 'money', signature: 'moneyCurrency(money) -> string', description: 'Extracts the currency code from a money value.' },
    { name: 'moneyAdd', category: 'money', signature: 'moneyAdd(money, money) -> money', description: 'Adds two money values with the same currency.' },
    { name: 'moneySum', category: 'money', signature: 'moneySum(array<money>) -> money', description: 'Sums money values in an array when all currencies match.' },
    { name: 'valid', category: 'mip', signature: 'valid(fieldRef) -> boolean', description: 'Returns whether a field currently has zero validation errors.' },
    { name: 'relevant', category: 'mip', signature: 'relevant(fieldRef) -> boolean', description: 'Returns whether a field is currently relevant.' },
    { name: 'readonly', category: 'mip', signature: 'readonly(fieldRef) -> boolean', description: 'Returns whether a field is currently readonly.' },
    { name: 'required', category: 'mip', signature: 'required(fieldRef) -> boolean', description: 'Returns whether a field is currently required.' },
    { name: 'prev', category: 'repeat', signature: 'prev() -> object | null', description: 'Returns the previous repeat row object, or null at the boundary.' },
    { name: 'next', category: 'repeat', signature: 'next() -> object | null', description: 'Returns the next repeat row object, or null at the boundary.' },
    { name: 'parent', category: 'repeat', signature: 'parent() -> object | null', description: 'Returns the parent repeat row or enclosing group object.' },
    { name: 'instance', category: 'instance', signature: 'instance(string, string?) -> any', description: 'Reads data from a named instance, optionally at a dotted path.' },
];
