/** @filedesc WASM bridge barrel — re-exports runtime + tools APIs (ADR 0050); same `wasmXxx` names as before. */

export {
    initWasm,
    isWasmReady,
    wasmAnalyzeFEL,
    wasmApplyMigrationsToResponseData,
    wasmCoerceFieldValue,
    wasmEvalFEL,
    wasmEvalFELWithContext,
    wasmEvalFELWithTrace,
    wasmEvaluateDefinition,
    wasmEvaluateScreenerDocument,
    wasmGetFELDependencies,
    wasmItemAtPath,
    wasmItemLocationAtPath,
    wasmNormalizeIndexedPath,
    wasmPrepareFelExpression,
    wasmResolveOptionSetsOnDefinition,
} from './wasm-bridge-runtime.js';

export type { WasmFelContext, FelTraceStep, FelTraceResult } from './wasm-bridge-runtime.js';

export {
    initWasmTools,
    isWasmToolsReady,
    wasmAssembleDefinition,
    wasmCollectFELRewriteTargets,
    wasmDetectDocumentType,
    wasmExecuteMapping,
    wasmExecuteMappingDoc,
    wasmExtractDependencies,
    wasmFindRegistryEntry,
    wasmGenerateChangelog,
    wasmJsonPointerToJsonPath,
    wasmLintDocument,
    wasmLintDocumentWithRegistries,
    wasmListBuiltinFunctions,
    wasmParseFEL,
    wasmParseRegistry,
    wasmPlanSchemaValidation,
    wasmPrintFEL,
    wasmRewriteFelForAssembly,
    wasmRewriteFELReferences,
    wasmRewriteMessageTemplate,
    wasmTokenizeFEL,
    wasmTryLiftConditionGroup,
    wasmValidateExtensionUsage,
    wasmValidateLifecycleTransition,
    wasmWellKnownRegistryUrl,
} from './wasm-bridge-tools.js';
