/**
 * @module formspec-types
 *
 * TypeScript types generated from the Formspec JSON schemas.
 * Zero runtime dependencies. Shared across all packages as the
 * canonical type vocabulary for Formspec documents.
 *
 * Types are auto-generated by scripts/generate-types.mjs.
 * Re-run: npm run types:generate
 */

// Re-export everything from generated schemas
export * from './generated/index.js';

// Widget vocabulary — canonical widget ↔ component mappings
export {
  KNOWN_COMPONENT_TYPES,
  SPEC_WIDGET_TO_COMPONENT,
  COMPONENT_TO_HINT,
  COMPATIBILITY_MATRIX,
  widgetTokenToComponent,
} from './widget-vocabulary.js';

// Backwards-compatible aliases (consumers use Form-prefixed names)
export type { Shape as FormShape } from './generated/definition.js';
export type { Variable as FormVariable } from './generated/definition.js';
export type { Instance as FormInstance } from './generated/definition.js';
export type { OptionEntry as FormOption } from './generated/definition.js';

// ─── Augmented Bind type ─────────────────────────────────────────────
// The generated Bind.default is typed as { [k: string]: unknown } because
// the schema has no type constraint on it. In practice, default can be any
// JSON value (number, string, null, object, etc.). This augmentation
// widens it to `unknown` so consumers don't need casts.

import type {
  Item, Presentation, Route, Bind,
  FormDefinition as GeneratedFormDefinition,
  Screener as GeneratedScreener,
} from './generated/definition.js';

export type FormBind = Omit<Bind, 'default'> & {
  default?: unknown;
};

// ─── Augmented Item type ─────────────────────────────────────────────
// The generated Item type only includes base properties (key, type, label).
// Conditional properties from the schema's if/then (children, dataType, etc.)
// fall through the [k: string]: unknown index signature as `unknown`.
// This augmentation adds them explicitly so consumers don't need casts.

/**
 * A form item with all conditional properties explicitly typed.
 * Extends the generated Item with properties the schema adds
 * conditionally based on item type (group, field, display).
 */
export type FormItem = Item & {
  // Group properties
  children?: FormItem[];
  repeatable?: boolean;
  minRepeat?: number;
  maxRepeat?: number;
  $ref?: string;
  keyPrefix?: string;

  // Field properties
  dataType?: 'string' | 'text' | 'integer' | 'decimal' | 'boolean' | 'date'
    | 'dateTime' | 'time' | 'uri' | 'attachment' | 'choice' | 'multiChoice' | 'money'
    | (string & {});
  currency?: string;
  precision?: number;
  prefix?: string;
  suffix?: string;
  options?: { value: string; label: string }[];
  optionSet?: string;
  initialValue?: unknown;
  semanticType?: string;
  prePopulate?: { instance: string; path: string; editable?: boolean };

  // Shared conditional
  presentation?: Presentation;

  // Inline bind shorthand — the engine supports placing bind properties
  // directly on items. These pass through the Item index signature as
  // unknown; this augmentation types them explicitly.
  relevant?: string;
  visible?: string;
  required?: string;
  calculate?: string;
  readonly?: string;
  constraint?: string;
  message?: string;
};

// ─── Augmented Screener type ──────────────────────────────────────────
// The generated Screener requires routes as a non-empty tuple [Route, ...Route[]]
// per the schema's minItems: 1 constraint. During authoring, a screener starts
// with empty routes. The `enabled` flag is an authoring-layer soft-delete
// not present in the schema.

export type FormScreener = Omit<GeneratedScreener, 'items' | 'routes'> & {
  items: FormItem[];
  routes: Route[];
  binds?: FormBind[];
  enabled?: boolean;
};

// ─── Augmented FormDefinition type ────────────────────────────────────
// The generated FormDefinition is schema-strict. This augmentation:
// - Uses FormItem[] for items (explicit conditional properties)
// - Makes status optional (omitted during draft creation)
// - Uses FormScreener (authoring-friendly)
// - Adds index signature to formPresentation (dynamic property access)

export type FormDefinition = Omit<
  GeneratedFormDefinition,
  'items' | 'status' | 'screener' | 'formPresentation' | 'binds'
> & {
  items: FormItem[];
  status?: GeneratedFormDefinition['status'];
  binds?: FormBind[];
  screener?: FormScreener;
  formPresentation?: GeneratedFormDefinition['formPresentation'] & {
    [k: string]: unknown;
  };
};

// ─── ProjectBundle ──────────────────────────────────────────────────
// The four exportable artifacts as a single bundle.
// Used across chat, studio-core, and core for serialization and snapshots.

import type { ComponentDocument } from './generated/component.js';
import type { ThemeDocument } from './generated/theme.js';
import type { MappingDocument } from './generated/mapping.js';

export interface ProjectBundle {
  /** The form definition artifact. */
  definition: FormDefinition;
  /** The component (UI tree) artifact. */
  component: ComponentDocument;
  /** The theme (presentation) artifact. */
  theme: ThemeDocument;
  /** Named collection of mapping (data transform) artifacts. */
  mappings: Record<string, MappingDocument>;
  /** Locale documents keyed by BCP 47 code (present only when locales are loaded). */
  locales?: Record<string, unknown>;
}
