/**
 * Mapping command handlers.
 *
 * The Formspec mapping document defines bidirectional transforms between form
 * responses (source) and external data schemas (target).
 *
 * All handlers return `{ rebuildComponentTree: false }` because mapping
 * mutations do not alter the definition item tree structure.
 *
 * @module handlers/mapping
 */
import type { CommandHandler } from '../types.js';
import { RuntimeMappingEngine } from 'formspec-engine';
import type { FormItem } from 'formspec-types';

export const mappingHandlers: Record<string, CommandHandler> = {

  'mapping.setProperty': (state, payload) => {
    const { property, value } = payload as { property: string; value: unknown };
    if (value === null) {
      delete (state.mapping as any)[property];
    } else {
      (state.mapping as any)[property] = value;
    }
    return { rebuildComponentTree: false };
  },

  'mapping.setTargetSchema': (state, payload) => {
    const { property, value } = payload as { property: string; value: unknown };
    if (!state.mapping.targetSchema) state.mapping.targetSchema = {};
    if (value === null) {
      delete state.mapping.targetSchema[property];
    } else {
      state.mapping.targetSchema[property] = value;
    }
    return { rebuildComponentTree: false };
  },

  'mapping.addRule': (state, payload) => {
    const p = payload as { sourcePath?: string; targetPath?: string; transform?: string; insertIndex?: number };
    if (!state.mapping.rules) state.mapping.rules = [];

    const rule: any = {};
    if (p.sourcePath !== undefined) rule.sourcePath = p.sourcePath;
    if (p.targetPath !== undefined) rule.targetPath = p.targetPath;
    rule.transform = p.transform ?? 'preserve';

    if (p.insertIndex !== undefined) {
      (state.mapping.rules as any[]).splice(p.insertIndex, 0, rule);
    } else {
      (state.mapping.rules as any[]).push(rule);
    }
    return { rebuildComponentTree: false };
  },

  'mapping.setRule': (state, payload) => {
    const { index, property, value } = payload as { index: number; property: string; value: unknown };
    const rules = state.mapping.rules as any[];
    if (!rules?.[index]) throw new Error(`Rule not found at index: ${index}`);
    rules[index][property] = value;
    return { rebuildComponentTree: false };
  },

  'mapping.deleteRule': (state, payload) => {
    const { index } = payload as { index: number };
    if (!state.mapping.rules) return { rebuildComponentTree: false };
    (state.mapping.rules as any[]).splice(index, 1);
    return { rebuildComponentTree: false };
  },

  'mapping.reorderRule': (state, payload) => {
    const { index, direction } = payload as { index: number; direction: 'up' | 'down' };
    const rules = state.mapping.rules as any[];
    if (!rules) return { rebuildComponentTree: false };
    const target = direction === 'up' ? index - 1 : index + 1;
    if (target < 0 || target >= rules.length) return { rebuildComponentTree: false };
    [rules[index], rules[target]] = [rules[target], rules[index]];
    return { rebuildComponentTree: false };
  },

  'mapping.setAdapter': (state, payload) => {
    const { format, config } = payload as { format: string; config: unknown };
    if (!(state.mapping as any).adapters) (state.mapping as any).adapters = {};
    (state.mapping as any).adapters[format] = config;
    return { rebuildComponentTree: false };
  },

  'mapping.setDefaults': (state, payload) => {
    const { defaults } = payload as { defaults: Record<string, unknown> };
    (state.mapping as any).defaults = defaults;
    return { rebuildComponentTree: false };
  },

  'mapping.autoGenerateRules': (state, payload) => {
    const p = payload as { scopePath?: string; priority?: number; replace?: boolean };
    if (!state.mapping.rules) state.mapping.rules = [];

    const rules = state.mapping.rules as any[];

    if (p.replace) {
      // Remove previously auto-generated rules
      for (let i = rules.length - 1; i >= 0; i--) {
        if (rules[i]['x-autoGenerated']) rules.splice(i, 1);
      }
    }

    // Collect all field paths
    const covered = new Set(rules.map((r: any) => r.sourcePath));
    const fieldPaths: string[] = [];
    const walk = (items: FormItem[], prefix: string) => {
      for (const item of items) {
        const path = prefix ? `${prefix}.${item.key}` : item.key;
        if (item.type === 'field') fieldPaths.push(path);
        if (item.children) walk(item.children, path);
      }
    };
    walk(state.definition.items, p.scopePath ?? '');

    for (const path of fieldPaths) {
      if (!covered.has(path)) {
        rules.push({
          sourcePath: path,
          targetPath: path,
          transform: 'preserve',
          priority: p.priority ?? -1,
          'x-autoGenerated': true,
        });
      }
    }

    return { rebuildComponentTree: false };
  },

  'mapping.setExtension': (state, payload) => {
    const { key, value } = payload as { key: string; value: unknown };
    if (value === null) {
      delete (state.mapping as any)[key];
    } else {
      (state.mapping as any)[key] = value;
    }
    return { rebuildComponentTree: false };
  },

  'mapping.setRuleExtension': (state, payload) => {
    const { index, key, value } = payload as { index: number; key: string; value: unknown };
    const rules = state.mapping.rules as any[];
    if (!rules?.[index]) throw new Error(`Rule not found at index: ${index}`);
    if (value === null) {
      delete rules[index][key];
    } else {
      rules[index][key] = value;
    }
    return { rebuildComponentTree: false };
  },

  'mapping.addInnerRule': (state, payload) => {
    const p = payload as {
      ruleIndex: number; sourcePath?: string; targetPath?: string;
      transform?: string; insertIndex?: number;
    };
    const rules = state.mapping.rules as any[];
    if (!rules?.[p.ruleIndex]) throw new Error(`Rule not found at index: ${p.ruleIndex}`);

    const rule = rules[p.ruleIndex];
    if (!rule.innerRules) rule.innerRules = [];

    const inner: any = {};
    if (p.sourcePath !== undefined) inner.sourcePath = p.sourcePath;
    if (p.targetPath !== undefined) inner.targetPath = p.targetPath;
    inner.transform = p.transform ?? 'preserve';

    if (p.insertIndex !== undefined) {
      rule.innerRules.splice(p.insertIndex, 0, inner);
    } else {
      rule.innerRules.push(inner);
    }
    return { rebuildComponentTree: false };
  },

  'mapping.setInnerRule': (state, payload) => {
    const { ruleIndex, innerIndex, property, value } = payload as {
      ruleIndex: number; innerIndex: number; property: string; value: unknown;
    };
    const rules = state.mapping.rules as any[];
    if (!rules?.[ruleIndex]?.innerRules?.[innerIndex]) throw new Error('Inner rule not found');
    rules[ruleIndex].innerRules[innerIndex][property] = value;
    return { rebuildComponentTree: false };
  },

  'mapping.deleteInnerRule': (state, payload) => {
    const { ruleIndex, innerIndex } = payload as { ruleIndex: number; innerIndex: number };
    const rules = state.mapping.rules as any[];
    if (!rules?.[ruleIndex]?.innerRules) throw new Error('Inner rules not found');
    rules[ruleIndex].innerRules.splice(innerIndex, 1);
    return { rebuildComponentTree: false };
  },

  'mapping.reorderInnerRule': (state, payload) => {
    const { ruleIndex, innerIndex, direction } = payload as {
      ruleIndex: number; innerIndex: number; direction: 'up' | 'down';
    };
    const rules = state.mapping.rules as any[];
    if (!rules?.[ruleIndex]?.innerRules) throw new Error('Inner rules not found');
    const inner = rules[ruleIndex].innerRules;
    const target = direction === 'up' ? innerIndex - 1 : innerIndex + 1;
    if (target < 0 || target >= inner.length) return { rebuildComponentTree: false };
    [inner[innerIndex], inner[target]] = [inner[target], inner[innerIndex]];
    return { rebuildComponentTree: false };
  },

  'mapping.preview': (state, payload) => {
    const {
      sampleData,
      direction,
      ruleIndices,
    } = payload as { sampleData: Record<string, unknown>; direction?: string; ruleIndices?: number[] };

    const mappingDoc = structuredClone(state.mapping) as any;
    if (Array.isArray(ruleIndices) && Array.isArray(mappingDoc.rules)) {
      mappingDoc.rules = ruleIndices
        .map(index => mappingDoc.rules[index])
        .filter((rule: unknown) => rule !== undefined);
    }

    const runtime = new RuntimeMappingEngine(mappingDoc);
    const result = direction === 'reverse'
      ? runtime.reverse(sampleData)
      : runtime.forward(sampleData);

    return {
      rebuildComponentTree: false,
      output: result.output,
      diagnostics: result.diagnostics,
      appliedRules: result.appliedRules,
      direction: result.direction,
    };
  },
};
