/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const evalFEL: (a: number, b: number, c: number, d: number, e: number) => void;
export const evalFELWithContext: (a: number, b: number, c: number, d: number, e: number) => void;
export const parseFEL: (a: number, b: number) => number;
export const printFEL: (a: number, b: number, c: number) => void;
export const getFELDependencies: (a: number, b: number, c: number) => void;
export const extractDependencies: (a: number, b: number, c: number) => void;
export const analyzeFEL: (a: number, b: number, c: number) => void;
export const collectFELRewriteTargets: (a: number, b: number, c: number) => void;
export const rewriteFELReferences: (a: number, b: number, c: number, d: number, e: number) => void;
export const rewriteMessageTemplate: (a: number, b: number, c: number, d: number, e: number) => void;
export const listBuiltinFunctions: (a: number) => void;
export const normalizeIndexedPath: (a: number, b: number, c: number) => void;
export const itemAtPath: (a: number, b: number, c: number, d: number, e: number) => void;
export const itemLocationAtPath: (a: number, b: number, c: number, d: number, e: number) => void;
export const detectDocumentType: (a: number, b: number, c: number) => void;
export const jsonPointerToJsonPath: (a: number, b: number, c: number) => void;
export const planSchemaValidation: (a: number, b: number, c: number, d: number, e: number) => void;
export const lintDocument: (a: number, b: number, c: number) => void;
export const lintDocumentWithRegistries: (a: number, b: number, c: number, d: number, e: number) => void;
export const evaluateDefinition: (a: number, b: number, c: number, d: number, e: number) => void;
export const assembleDefinition: (a: number, b: number, c: number, d: number, e: number) => void;
export const executeMapping: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const parseRegistry: (a: number, b: number, c: number) => void;
export const findRegistryEntry: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const validateLifecycleTransition: (a: number, b: number, c: number, d: number) => number;
export const wellKnownRegistryUrl: (a: number, b: number, c: number) => void;
export const validateExtensionUsage: (a: number, b: number, c: number, d: number, e: number) => void;
export const generateChangelog: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const executeMappingDoc: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number, b: number, c: number) => void;
